
-- RESTORE SCRIPT FOR SSCT 
 
RESTORE DATABASE [SSCT_TEST] 
FROM DISK = '\\MKD20\z$\sql_backups\SSCT\SSCT-111407-001815-1.FULL', 
         DISK = '\\MKD20\z$\sql_backups\SSCT\SSCT-111407-001815-2.FULL' 
WITH  
MOVE 'SSCT_DATA-P1'  TO 'S:\SQL_DATA\SSCT.MDF',  
MOVE 'SSCT_DATA-P2' TO 'P:\SQL_DATA\SSCT_DATA-P2.NDF',  
MOVE 'SSCT_LOG-P' TO 'R:\SQL_LOGS\SSCT_TEST_log.LDF',  
REPLACE 

EXEC sp_who1

DBCC INPUTBUFFER(64)



