
USE master; 
GO 
ALTER DATABASE msdb
MODIFY FILE (NAME = MSDBData,FILENAME = 'X:\MSSQL\DATA\MSDBData.mdf'); 
GO 
ALTER DATABASE msdb
MODIFY FILE (NAME = MSDBLog, FILENAME = 'Y:\MSSQL\LOG\MSDBLog.ldf'); 
GO 
